failFast: true

potential-bugs:
  UnsafeCast:
    active: false

style:
  ExpressionBodySyntax:
    active: false
  ForbiddenComment:
    active: true
    values: 'FIXME:,STOPSHIP:'
  MagicNumber:
    active: false
